name: fadi_bring_me_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter 
  flutter_launcher_icons: ^0.14.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/


flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/BringMe_Icon.png