name: fadi_bring_me_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  dropdown_textfield: ^1.2.0
  easy_url_launcher: ^0.0.7
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  image_picker: ^1.1.2
  loading_elevated_button: ^1.0.0+2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  social_login_buttons: ^1.0.7
  social_media_buttons: ^1.0.0
  timer_snackbar: ^0.0.3
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/gif/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/BringMe_Icon.png

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBLACKITALIC.OTF
          weight: 900
          style: italic
        - asset: assets/fonts/SFPRODISPLAYHEAVYITALIC.OTF
          weight: 800
          style: italic
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 700
        - asset: assets/fonts/SFPRODISPLAYLIGHTITALIC.OTF
          weight: 300
          style: italic
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
          weight: 400
        - asset: assets/fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF
          weight: 600
          style: italic
        - asset: assets/fonts/SFPRODISPLAYTHINITALIC.OTF
          weight: 100
          style: italic
        - asset: assets/fonts/SFPRODISPLAYULTRALIGHTITALIC.OTF
          weight: 200
          style: italic
