name: fadi_bring_me_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/logo/BringMe_Logo.png
   - assets/images/Flag_of_Belgium.png
   - assets/images/Flag_of_Denmark.png
   - assets/images/Flag_of_Finland.png
   - assets/images/Flag_of_France.png
   - assets/images/Flag_of_GB.jpg
   - assets/images/Flag_of_Germany.png
   - assets/images/Flag_of_Syria.png

